[system]
compatible=ds-uspd
bootloader=barebox
mountprefix=/mnt/rauc

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs_a
type=ext4
bootname=system0

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs_b
type=ext4
bootname=system1